name: Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Change if your default branch is different
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: imagedata
        run: python3 loadImageData.py

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1  # Adjust to match your Jekyll version
          bundler-cache: true

      - name: Install Jekyll and Dependencies
        run: bundle install

      - name: Build Jekyll Site
        run: bundle exec jekyll build --destination _site

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jekyll-site
          path: _site  # Path to the built site
          retention-days: 1  # Adjust if needed

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
