name: Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Change if your default branch is different
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 1

      - name: Remove Travel images
        run: rm -rf travelImages

      - name: imagedata
        run: python3 loadImageData.py

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2  # Adjust to match your Jekyll version
          bundler-cache: true

      - name: Install Jekyll and Dependencies
        run: bundle install

      - name: Build Jekyll Site
        run: bundle exec jekyll build --destination _site

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v3
        id: deployment
        with:
          name: github-pages  # ✅ Must be exactly "github-pages"
          path: _site  # ✅ Path to the cleaned site
          retention-days: 1  # Adjust if needed
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
